name: Deploy
on: [push]
jobs:

  build:
    name: Pull and Build
    runs-on: ubuntu-latest
    steps:
    - name: Pull and Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PW }}
        script: |
              cd /var/www/me
              sh pull-and-build.sh
