name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Login
      run: |
        ssh root@93.177.64.130
        $SERVER_PW
      env:
        SERVER_HOST: SERVER_HOST
        SERVER_PW: SERVER_PW
        
    - name: Change directory
      run: cd /var/www/me

    - name: Run Shell Script 
      run: sh pull-and-build.sh
